//POST http://www.atos8.local:8080/api/v1/church
PATCH https://api.godaddy.com/v1/domains/atos8.com/records HTTP/1.1
Authorization: sso-key fY15ZyEcodfB_6UuC23ZR3mp8gnUV8igHwF:MGNwjeSoYRyw2L98KVhLNS
Content-Type: application/json


{
    "data": "45.164.244.54",
    "name": "piba",
    "ttl": 600,
    "type": "A"
}
