version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/backend/html
      - ./docker/local/app.conf:/etc/nginx/sites-enabled/default
    networks:
      - atos8-backend-network
    ports:
      - 8000:8000
networks:
  atos8-backend-network:
    driver: bridge
