GET http://localhost:8000/api/users/10
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|WDLnX7OsIyrOz2bfeoX7hS2KzWEr0yHdJSHPBtpI

###
POST http://localhost:8000/api/employees
Content-Type: application/json
Accept: application/json
Authorization: Bearer 48|u3cWECP8s4nvl25Tj6vnAZl3KdYAlZBZ6MQ3Oswb

{
    "user": {
        "name": "Elaine Richelline",
        "email": "elainerichell@gmail.com",
        "password": "123456",
        "confirm_password": "123456",
        "type": "web",
        "roles": []
    },
    "employee": {
        "first_name": "Elaine",
        "last_name": "Richelline",
        "gender": "male",
        "birth_date": "29/12/1986",
        "cpf": "06545218409",
        "rg": "7449629",
        "cell_phone": "81999002918"
    }

}

###
POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@atos242.com",
  "password": "123456"
}
