###
GET http://dev.atos8.local:8080/api/v1/financial/entries?startDate=2023-09-06&endDate=2023-09-10
Content-Type: application/json
Accept: application/json
Authorization: Bearer 35|zeNnOUyfRwDhHMxIyFNmq3DuPX2mlCAsrCi8rJoS


###
GET http://dev.atos8.local:8080/api/v1/financial/entries?dates=2024-05,2024-04&page=2
Content-Type: application/json
Accept: application/json
Authorization: Bearer 12|oEnOylAYD2jd478i7o8Glt1N5v8edjBCKe4oud4M




###
PUT http://dev.atos8.local:8080/api/v1/financial/entries/48
Content-Type: application/json
Accept: application/json
Authorization: Bearer 35|zeNnOUyfRwDhHMxIyFNmq3DuPX2mlCAsrCi8rJoS

{
    "entryType":"offers",
    "transactionType":"doc_ted_tev",
    "transactionCompensation":"compensated",
    "dateTransactionCompensation": "2023-10-14T03:00:00.000Z",
    "dateEntryRegister": "2023-07-01",
    "amount":500,
    "recipient":null,
    "memberId":null,
    "reviewerId":1
}

###
GET http://dev.atos8.local:8080/api/v1/financial/entries/48
Content-Type: application/json
Accept: application/json
Authorization: Bearer 35|zeNnOUyfRwDhHMxIyFNmq3DuPX2mlCAsrCi8rJoS

