POST https://www.atos8.com/api/v1/church
//POST https://www.atos8.com/api/v1/church
Content-Type: application/json


{
    "church": {
        "tenant_id": "stage",
        "plan_id": 1,
        "name": "Igreja Staging",
        "activated": true,
        "doc_type": "cnpj",
        "doc_number": "290837827203126"
    },
    "user": {
        "admin_email_tenant": "stage@atos8.com",
        "pass_admin_email_tenant": "123456",
        "confirm_pass_admin_email_tenant": "123456",
        "user_activated_tenant": true,
        "changed_password": false,
        "access_quantity": 0,
        "user_type_tenant": "web",
        "roles": ["admin"]
    },
    "details": {
        "fullName": "Administrador",
        "avatar": "",
        "type": "",
        "title": "Administrador",
        "gender": "male",
        "phone": "81999002918",
        "address": "Rua Aluísio de Azevedo, 378",
        "district": "Jardim Atlântico",
        "city": "Olinda",
        "country": "Brasil",
        "birthday": "29121986"
    }
}
